### ISSUE TITLE
Specifying the attributes of each object more rigorously

### ISSUE THREAD

**Issue by domenic** [w3c/longtasks#11]
Each object (TaskAttributionTiming, PerformanceLongTaskTiming) needs to specify getter algorithms for each of its attributes, including inherited attributes. Some of these will be constant:

> (PerformanceLongTaskTiming) The `entryType` attribute's getter must return "`longtask`"

> (TaskAttributionTiming) The `startTime` attribute's getter must return 0

(Note the addition of `'s getter` which is not in the current spec. Just a nit.)

---

However for the non-constant ones, you need to be a bit more careful, since you need the processing model to "set" them. This is a bit strange because they only have getters (they are readonly). If you want to be rigorous, you end up defining this like so:

> Each TaskAttributionTiming has an associated frame name, frame ID, and frame src.
>
> ...
>
> The frameName attribute's getter must return this TaskAttributionTiming's associated frame name.
>
> ...
>
> (in the processing model) Set _attribution_'s associated frame name to the value of _iframe_'s name content attribute, or null if the attribute is absent.

That is, you have the "private variable" of "associated frame name" which the public `frameName` attribute's getter returns.

---

There is a less rigorous version which you can get away with without much fuss, which is this:

> The frameName attribute's getter must return the value it is initialized with during construction.
>
> ...
>
> (in the processing model) Initialize _attribution_'s frameName attribute to the value of _iframe_'s name content attribute, or null if the attribute is absent.

I think I would probably recommend this less rigorous version for this spec.

---

The main thing to avoid is having "must" algorithms which are meaningless. For example, the current spec says

> The frameName attribute must return DOMString with culprit iframe's name attribute.

That's not helpful since we have no idea how to determine the culprit. How do you implement that getter? It turns out the answer is in the processing model section. That reality is better reflected by one of the above two formulations. You can keep the helpful content here as a description, but not as a MUST algorithm. Example:

> The frameName attribute's getter must return the value it is initialized with during construction. This will be derived from the culprit's iframe's name attribute.

**Comment by spanicker** [comment]
@igrigorik - should this issue be moved to PerformanceEntry's spec repo ?

**Comment by tdresser** [comment]
I think Domenic's change fixed this.
