### ISSUE TITLE
Better understand correlating long tasks from different iframes

### ISSUE THREAD

**Issue by spanicker** [w3c/longtasks#18]
[cover bug for exploration, not sure if this is a problem yet]
Understand how long tasks from different iframes could be correlated on a timeline.
Long tasks are reported relative to the observing document's time-origin, so it's hard for multiple cross-origin frames to collaborate eg. if the parent / host page and Ads in separate frames.
Is this problematic?

The host page and the Ads iframe will both observe the same long task but will receive separate start-times (relative to their own document time-origin). The host page cannot see detailed attribution but the Ad iframe can see this, and may want to relay more details to the host page.

**Comment by noamr** [comment]
Closing this, not planning to explore ATM
