### ISSUE TITLE
Does PerformanceLongTaskTiming's attribution attribute always return the same value?

### ISSUE THREAD

**Issue by foolip** [w3c/longtasks#20]
https://wicg.github.io/longtasks/#sec-PerformanceLongTaskTiming

If so, add `[SameObject]` to the Web IDL. If not, some prose needs to explain when a new value is returned and not.

@domenic might be interested.

**Comment by spanicker** [comment]
I'm a bit puzzled by the question. No it doesn't return the same value. A new attribution object is created for each PerformanceLongTaskTiming entry. 
Internally this is a HeapVector<Member<TaskAttributionTiming>> 
See:
https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/timing/PerformanceLongTaskTiming.h?l=42
https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/timing/PerformanceLongTaskTiming.cpp?dr&l=46

**Comment by foolip** [comment]
I mean whether each instance of PerformanceLongTaskTiming returns the same value each the attribution attribute is accessed, and I assume that it should.

Here are two APIs with a readonly FrozenArray<T> that uses [SameObject]:
https://drafts.csswg.org/css-font-loading/#FontFaceSet-interface
https://notifications.spec.whatwg.org/#api

**Comment by foolip** [comment]
More context: lots of APIs defined using Web IDL have historically failed to uphold the reasonable assumption that `x.y === x.y` where `y` is some array. That is fixed by returning the same object each time, and `FrozenArray<T>` was introduced so that it's not possible to change the array in-place, which would be weird. (This is also why a `sequence<T>` attribute isn't allowed in Web IDL, "Sequences must not be used as the type of an attribute or constant.")

**Comment by domenic** [comment]
Even more context: `[SameObject]` is largely documentation of facts already stated normatively in the spec, namely that the value is only initialized once and never changed. I think for Gecko it might help their code-generator; for Blink it's complicated...

**Comment by spanicker** [comment]
Thanks for the context & details folks! I've update the code, and will update the spec as well.

**Comment by igrigorik** [comment]
@spanicker did you land the necessary update? Can we close this?

**Comment by spanicker** [comment]
updated spec & explainer to match IDL
