### ISSUE TITLE
Remove "Not Ready For Implementation"

### ISSUE THREAD

**Issue by igrigorik** [w3c/longtasks#22]
I believe the plan was to remove this?

**Comment by spanicker** [comment]
Does the spec now live here: https://github.com/w3c/longtasks/blob/master/index.html
I updated it - but the hosted html is not updating?

**Comment by igrigorik** [comment]
The HTML needs to live on the gh-pages branch. I believe we have a job that does this automagically.. @plehegar is this something you can help with?

**Comment by tabatkins** [comment]
Or better, go into settings for the repo and set the GH Pages branch to master.  (You can't even use gh-pages anymore for new stuff; it's merely preserved for legacy repos that were using it previously.)

**Comment by plehegar** [comment]
I haven't setup bikes he'd on github recently so it will take me time to figure it out again. I'd you know how,  go ahead. Otherwise @xiaoqian may be able to do it quickly.

**Comment by plehegar** [comment]
Meant to include @suisin

**Comment by spanicker** [comment]
@tabatkins any advise here for setting up bikeshed (we moved from WICG to w3c)?

**Comment by yoavweiss** [comment]
Fixed by #23

**Comment by plehegar** [comment]
really fixed in master now, using a variant of https://gist.github.com/domenic/ec8b0fc8ab45f39403dd
