### ISSUE TITLE
How to clear longtask entries?

### ISSUE THREAD

**Issue by yoshuawuyts** [w3c/longtasks#27]
I couldn't find anything in the spec on how long task entries get cleared from the performance timeline. I probably don't need to explain why a full timing buffer isn't great haha.

To my knowledge the current spec only defines:
- `performance.clearMarks()`
- `performance.clearMeasures()`
- `performance.clearResourceTimings()`

How would you go about clearing these? Did I miss something?

**Comment by igrigorik** [comment]
LT does not have an associated buffer (it's only accessible via PerformanceObserver interface), so there is nothing to clear.. :)

p.s. there are a few loose ends that need to resolved -- see https://github.com/w3c/performance-timeline/issues/81.

**Comment by yoshuawuyts** [comment]
Oh neat! :D - Yeah that totally solves it haha, guess I should've realized
it sooner. Thanks!
