### ISSUE TITLE
PerformanceLongTaskTiming millisecond round vs floor

### ISSUE THREAD

**Issue by npm1** [w3c/longtasks#29]
Currently, we use floor in PerformanceLongTaskTiming, but this means that the accuracy of the timestamps is not as good as it could be. On the other hand, using round would mean that the end_time would sometimes point to a timestamp in the future. What is a good solution that improves accuracy while not causing issues?

**Comment by igrigorik** [comment]
@npm1 just to clarify, who is "we" in this discussion? 

From the spec:
- Set the selected task’s end time to the value be the value that would be returned by the Performance object’s now() method.
- Set the selected task’s start time to the value be the value that would be returned by the Performance object’s now() method.
- Set newEntry’s duration attribute to end time minus start time

**Comment by npm1** [comment]
My bad, 'we' means chromium's Webkit. See:
https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/timing/PerformanceLongTaskTiming.cpp?l=14

**Comment by tdresser** [comment]
The spec states that "timing info provided is clamped to 1ms resolution", but doesn't state how clamping is performed. Is there a consistent defintion for "clamp" somewhere, or should we be more specific?

**Comment by igrigorik** [comment]
AFAIK, we don't have a formal definition for "clamp" anywhere. That said, we do have "Clock Resolution" guidance that sets a recommended floor as part of HR-Time: https://www.w3.org/TR/hr-time-3/#clock-resolution. We should probably (a) reference that in this spec, (b) raise the limit for particular field(s), (c) specify how to round.

**Comment by tdresser** [comment]
If we're going to be consistent everywhere, rounding doesn't work, as shown by npm@'s example of where rounding puts a timestamp into the future.

Perhaps flooring is the best choice?
@spanicker, any thoughts? 

Ilya, which limit are you referring to? The 5 microsecond limit suggested in the "Clock Resolution" guidance?

**Comment by igrigorik** [comment]
@tdresser yep. 

> On the other hand, using round would mean that the end_time would sometimes point to a timestamp in the future. What is a good solution that improves accuracy while not causing issues?

Arguably round() is the "improves accuracy" function, right? You may be overestimating in some cases, but the delta is at most 1/2ms. Honestly, I'm not sure the "in the future" is a big deal here?

**Comment by tdresser** [comment]
If we round into the future, a developer can just take `min(performance.now(), rounded_value)` to get a more accurate value.

Isn't that adequate justification for avoiding it?

**Comment by spanicker** [comment]
Personally I'd prefer to err on the side of more accurate timestamp - as we are asking devs to cross correlate long tasks with other things (events, frames etc).
Agree with Ilya that "in the future"  is not a huge deal for measurement usecase.

**Comment by spanicker** [comment]
The 1ms clamping is for security, and Tim brings up a good point that in theory the developer could get a more accurate timestamp with the min(performance.now, ...). So perhaps we should just leave this as is.

**Comment by igrigorik** [comment]
How can the attacker guarantee that their timestamp measurement is executed as the very last step in the task? Can you remind me on the attack / reason that led us to introduce the 1ms clamp?

**Comment by spanicker** [comment]
in theory the time at which the PO callback is invoked (via performance.now()) could be before the rounded "end time" reported in the long task entry.

For 1ms clamp see here:
https://docs.google.com/document/d/1w7TCMPZ1KtVbi9tuVRfM8d2yLi0Cl3NxNzb8AOgF7bo/edit#heading=h.nt77k1gdbw83

**Comment by igrigorik** [comment]
So, just to make sure I understand the vector here...

Today, an attacker can poll the timeline with setTimeout and observe differences between calls with a minimum of 1ms granularity. Within setTimeout callback, they can obtain a high-res timestamp and get a high-res duration between last recorded and current `performance.now()`. So, if the other code takes >1ms then they have a precise duration. How does LT, make this worse? We have a much high threshold (>50ms). Are we concerned about attribution?

**Comment by spanicker** [comment]
I think your question is about the general reason for clamping to 1ms in Long Tasks i.e. attack vector that Long Tasks adds over existing setTimeout.
I added you to the relevant threads in the security doc about this:
https://docs.google.com/document/d/1tIMI1gau_q6X5EBnjDNiFS5NWV9cpYJ5KKA7xPd3VB8/edit#
esprehn: "sub-ms lets you observe things that are very fast at a precision that we didn't really offer before. It's possible some of that is mitigated by the 50ms lower bound, but allowing you to set your own limit means letting you observe things like encryption tasks that take 0.01ms vs 0.02ms which is a bigger information leak."

The short answer is 50ms provides adequate protection, but we've talked about allowing developers to override this, the clamp was a safe and easy thing to do. However now that we talking about correlating the timestamp with event timing etc, this raises the question if that's still a good tradeoff.
(Also BTW setTimeout attacks will be mitigated with OOPIF architecture)

**Comment by igrigorik** [comment]
> The short answer is 50ms provides adequate protection, but we've talked about allowing developers to override this, the clamp was a safe and easy thing to do.

I'm assuming we would still set a minimum, like maximum budget for a frame (e.g. 16ms for 60Hz, 8ms for 120Hz, etc). At which point the precision is no worse than rAF-polling. Right?

Per Tim's comment in https://github.com/w3c/longtasks/issues/29#issuecomment-312301435, I'm thinking we can drop the 1ms clamp?

**Comment by spanicker** [comment]
dropping 1ms clamp SGTM.

**Comment by tdresser** [comment]
If security folks are good with it, SGTM.

**Comment by igrigorik** [comment]
Resolved via https://github.com/w3c/longtasks/commit/b634d268b9f74c31e649ca5ee4ab906a6503ab0c
