### ISSUE TITLE
Indicate script parse time in attribution 

### ISSUE THREAD

**Issue by spanicker** [w3c/longtasks#30]
Per discussion here: https://twitter.com/igrigorik/status/880194010010206208
for v2 script attribution: we want to distinguish between script compile (covers parse) and execution to cover the use case of slow parse time

Figure out what's the threshold for "slow parse" that is interesting to surface.

**Comment by addyosmani** [comment]
I like the idea of allowing sites to customize the threshold. Although the 50ms number came up as the threshold for slow parse in the thread, I'd wager we'll need to do some research before settling on a realistic number here.

**Comment by tdresser** [comment]
I think we'll want to split out script parse and compile from execution via attribution done through stack samples (#42), ideally.

Threshold customization is covered in issue #14.
