### ISSUE TITLE
remove index.html in the master branch

### ISSUE THREAD

**Issue by siusin** [w3c/longtasks#35]
`deploy.sh` will automatically generate a new `index.html` and deploy to the `gh-pages` branch... Shall we remove the `index.html` in the `master` branch to avoid inconsistency?

**Comment by igrigorik** [comment]
I believe we want to keep it, it's useful for editors working on .bs files.. as it provides a preview of the final HTML changes being made. Also, other Bikeshed specs keep it around as well - e.g. CSP, Fetch, etc.

**Comment by domenic** [comment]
Fetch does not. No WHATWG specs commit generated output to Git.

**Comment by spanicker** [comment]
the deploy.sh auto updating is broken - i.e. does not always update gh-pages (same issue for paint-timing), @plehegar was looking into it.
Once that issue is fixed we can remove the redundant index.html?
Alternately I could manually update gh-pages?

**Comment by siusin** [comment]
The bug in auto-update script should have been fixed by the last commit :) Let's wait for the next update of index.bs to see if there's any remaining bug.

Manual updates to the index.html of gh-pages will take effect in the [editor's draft](https://w3c.github.io/longtasks/).
