### ISSUE TITLE
Long tasks v2 scriptUrl -> scriptURL

### ISSUE THREAD

**Issue by domenic** [w3c/longtasks#36]
Not sure where to file this since long tasks v2 spec work doesn't seem too far along, but responding to some BlinkOn slides: just wanted to note it should be scriptURL, not scriptUrl, per https://w3ctag.github.io/design-principles/#casing-rules and https://url.spec.whatwg.org/#url-apis-elsewhere :)

**Comment by tdresser** [comment]
We'll try to keep this in mind, but I think this feedback is obsolete at this point.
