### ISSUE TITLE
toJSON

### ISSUE THREAD

**Issue by npm1** [w3c/longtasks#37]
toJSON() is now mandatory for PerformanceEntry. Should it also be explicitly added to the interface declarations for PerformanceLongTaskTiming and TaskAttributionTiming, which have additional attributes?

**Comment by marcoscaceres** [comment]
It's inherited from `PerformanceEntry`, so should just work. No need to add it again.

**Comment by npm1** [comment]
Yes, technically, but the implementation needs to be different because of the addition of new members in those interfaces. Does this deserve a mention in the spec?

**Comment by domenic** [comment]
My reading of https://heycam.github.io/webidl/#Default is that the additional attributes will not be included unless you give the subclasses their own toJSON() methods. This makes sense, as it doesn't do runtime polymorphic enumeration of all properties, but instead uses the static list encoded into its implementation.

**Comment by npm1** [comment]
Sorry, I didn't follow up on this before. From the last comment, I take it that we would prefer to add toJSON in the IDL of the interface that inherits from another which already has toJSON, if it has additional attributes?
