### ISSUE TITLE
Notes and action items from TPAC 2016

### ISSUE THREAD

**Issue by igrigorik** [w3c/longtasks#4]
1. Based on discussion at TPAC, I propose we transfer this repo to WICG.
2. We need to document security/privacy implications of this API
3. Collect and share benchmark data on overhead
4. Collect usage pattern data to help validate / firm up V2 attribution

/cc @yoavweiss @cwilso @marcoscaceres see (1). :)

**Comment by marcoscaceres** [comment]
@igrigorik, is there minutes we can point to? We need a couple of LGTMs/positive signals from vendors before transferring.

**Comment by yoavweiss** [comment]
Minutes: https://www.w3.org/2016/09/23-webperf-irc
Summary: https://docs.google.com/document/d/1RigHs7a4yRcVUt4fPswOZLKY_-tDlPiz8hPokBixHEk/edit

There were positive signals from all participants in the room. I think we can safely transfer the repo.

**Comment by marcoscaceres** [comment]
@spanicker, I've sent you an invite to the WICG. That should allow you to transfer ownership of this repo to the WICG.
