### ISSUE TITLE
Specify Possible "Task Types"

### ISSUE THREAD

**Issue by tdresser** [w3c/longtasks#40]
In order to provide attribution, we need a common notion of task types.

Let's come up with a proposal for a set of task types all UA's can agree on.

In the short term: 
* Don't name them script

Strawman: provide attribution for:
* Render steps
* Other browser work
* Posted tasks

**Comment by tdresser** [comment]
@npm1

**Comment by maxlgu** [comment]
Ping from crbug.com/759166 as it's getting stale.

**Comment by npm1** [comment]
We need to add some clarifications/fixes to the current API before we can consider extending it.

**Comment by npm1** [comment]
Discussed at TPAC. The resolution was that it's unclear what the classification should be. In particular, coarseness is tricky because if we want to start with a coarse classification and then make it more granular, that results in confusing metrics. For now, we're punting this for an indefinite amount of time.

**Comment by igrigorik** [comment]
Any reason why we shouldn't close this?

**Comment by npm1** [comment]
I was going to say no reason but I see that I already landed into the spec the 'rendering' and 'browser' possibilities into the |name| attribute of PerformanceLongTaskTiming. Should we roll this back so we don't have any kind of task types specified? Chrome has not implemented this yet.

I'd argue that task types of the future would be specified in a separate attribute (|name| already includes script origin information), so the granularity concern is not valid in this case. That is, if and when we add more task types, they will be added to a new attribute, so the granularity of |name| shall be unaffected.

**Comment by tdresser** [comment]
Rolling that spec change back and closing this issue is probably reasonable.

**Comment by domenic** [comment]
Closed by #50, thanks @npm!
