### ISSUE TITLE
Change name to be less confusing

### ISSUE THREAD

**Issue by npm1** [w3c/longtasks#47]
LongTasks can report long tasks that come from sources other than just scripts. Thus, the name should be renamed because 'script' makes it sound like it's only reporting tasks from scripts.

**Comment by igrigorik** [comment]
To clarify, which name is this referring to? :) Name of the spec, something else?

**Comment by npm1** [comment]
The |name| attribute of a TaskAttributionTiming object is currently 'script'.

**Comment by yoavweiss** [comment]
This is one takeaway from the F2F, where folks were surprised that LongTasks currently covers more than just scripts. We [discussed](https://docs.google.com/document/d/1bYMLTkjcyOZR5Jt3vrulzMSoS32zOFtwyH33f6hW_C8/edit#) changing the name attribute to "unknown" or "unclassified" (at least until we have full attribution).
