### ISSUE TITLE
Guidelines to contribute (send a pull request)

### ISSUE THREAD

**Issue by Marlysson** [w3c/longtasks#5]
I would send a pull request related to fix a broken link demo of site, but I read that it's necessary be member of "CG" but I am not , how send pull request?

**Comment by spanicker** [comment]
@yoavweiss  - can you advise ?

**Comment by yoavweiss** [comment]
@Marlysson - You can join the CG at https://www.w3.org/community/wicg/participants

You can send your PR before joining, but you'd have to join before those contributions can be merged (for IPR reasons).

Thanks! :)
