### ISSUE TITLE
The processing model only works for iframes, not object/embed/etc.

### ISSUE THREAD

**Issue by domenic** [w3c/longtasks#52]
Even after #51, we only handle iframe elements.

Is this an intentional "v1" restriction? If so we should be explicit. Or is it an accident that slipped through? If so we need to generalize the processing model to work for any "browsing context container".

**Comment by npm1** [comment]
@spanicker might have more context here. It appears that we would need to handle other cases in a case-by-case basis. For iframe/embed we'd like to use src, but for object we'd like to use data, and not sure what else can be a browsing context container.

**Comment by domenic** [comment]
What does Chrome implement?

I *think* the complete list should be embed, iframe, frame, object.

**Comment by npm1** [comment]
Ok, I did some testing and it looks like the longtasks are reported as you'd expect, except containerSrc is empty for object (due to the URL coming from data instead of src).

**Comment by tdresser** [comment]
Given that `frame` is effectively deprecated, I think we should probably stick to `embed`, `iframe`, and object. Does that sound reasonable?

**Comment by domenic** [comment]
I mean, embed and object are also kind of deprecated... I guess not formally in the spec.

I tend to think we should either shoot for modern-BC-containers only (= iframe and maybe in the future portal), or we should do all BC-containers (including frame).
