### ISSUE TITLE
Provide explanation for the 50ms threshold

### ISSUE THREAD

**Issue by marcelduran** [w3c/longtasks#59]
Throughout the specs, it's not clear why **50ms** was chosen as the long task duration threshold. Under [Security and privacy considerations](https://w3c.github.io/longtasks/#priv-sec), it just states such threshold also provides adequate protection against security attacks.

**Comment by npm1** [comment]
I see the spec mentions:

"RAIL performance model suggests that applications should respond in under 100ms to user input; for touch move and scrolling in under 16ms. Our goal with this API is to surface notifications about tasks that may prevent the application from hitting these targets."

But maybe the explanation of why 50ms should be made more explicit. @spanicker would you like to elaborate on this or should I do it?

**Comment by marcelduran** [comment]
[Measure Performance with the RAIL Model](https://developers.google.com/web/fundamentals/performance/rail#ux) has more info on the 50ms rationale too.
