### ISSUE TITLE
containerType is confusing

### ISSUE THREAD

**Issue by SilentImp** [w3c/longtasks#61]
Hi.

I am trying to implement longtask's logging on the project, but it's not clear how to find the source of problem from entry content.

![Screenshot 2019-04-05 at 17 16 03](https://user-images.githubusercontent.com/217308/55638267-15f50b80-57c7-11e9-8d4e-251333239e31.png)
MacOS 10.14.4
Chrome Version 73.0.3683.86 (Official Build) (64-bit)

May you please explain how to actually find what causing this longtask?
It may also be an example that may be added to the spec.

As far as I understand name `self` means that longstack was produced by current browser context, but in the same time I have containerType `iframe`, thats a little bit confusing.
Main source of information here: `TaskAttributionTiming`, but `containerName`, `containerId` and `containerSrc` are empty and I even don't clearly understand what exactly they should contain from specification. Example would be highly appreciated. 

With all best and kind regards. Anton.

**Comment by npm1** [comment]
Hi, yea that is kinda confusing... Looking at our implementation, all of the TaskAttributionTiming entries you'll get will have "iframe" as its `containerType`. So you should rely on `name`'s "self": the longtask was executed in your frame's context.

@yoavweiss @spanicker any idea on what we could do to fix the confusion caused by containerType?

**Comment by tdresser** [comment]
Should there be a "top-level" container type?

**Comment by domenic** [comment]
The spec currently says it should be left as uninitialized (i.e., step 6.4 does not execute), which means... what?

We should definitely set it to something else, either "top-level" or maybe null or the empty string. I kind of like null.

Related, if we fix #52, other containerTypes will exist.

**Comment by npm1** [comment]
I kind of dislike null because then a developer needs to go to the spec to understand what null means. "top-level" or similar is more intuitive.

**Comment by tdresser** [comment]
We're planning to go with "window".
