### ISSUE TITLE
Top-level browsing context scoping

### ISSUE THREAD

**Issue by annevk** [w3c/longtasks#75]
Why does this use top-level browsing context scoping? If A nests B and we run the event loop for B, we end up passing A's browsing context to the Long Tasks API from HTML's event loop algorithm. This seems rather weird. (And that in turn will do something with both A and B.)

**Comment by npm1** [comment]
Yea, I agree that it's a bit weird. What we want is to report longtasks to browsing contexts sharing the same renderer process (is this equivalent to sharing the same event loop, or can there be more than one event loop per renderer process?). Is there a concept for this in the spec we may use?

**Comment by annevk** [comment]
A browsing context can encompass multiple processes so perhaps using them at all is a problem here?

**Comment by npm1** [comment]
Ok, so we can change it to use the `docs` that are defined in the Update the rendering step.

**Comment by annevk** [comment]
Well, this is the only specification that update the rendering invokes with browsing contexts, right?

**Comment by yoavweiss** [comment]
@plehegar - could you clarify your comment from the last call?

**Comment by npm1** [comment]
Re-adding the requires-discussion label since I think we need to agree on the scope on which longtasks are reported. Right now, if If A nests B and B has a longtask then it may be reported in A when they share a process, regardless of origin (sure, implementation detail, but I think that's the current state).

**Comment by annevk** [comment]
That sounds very bad and indeed a bug.

**Comment by domenic** [comment]
It's not obvious it's bad, although it's bad that it wasn't discussed. Performance APIs are most useful when they measure all the things that affect you, and for long tasks, I think that would be everything in the same thread at least. (Which reduces to same process if we're ignoring tasks in workers, which I think this API does.)

But, we're currently moving toward restricting these sorts of process-wide APIs behind COOP+COEP. I'm not sure what attack exactly would be possible by detecting cross-site long tasks though...

**Comment by npm1** [comment]
I imagine this was discussed at some point before this API was shipped. @spanicker can you provide some context? Oh I found this relevant document but not clear to me who it was shared with outside of Google at the time. https://docs.google.com/document/d/1tIMI1gau_q6X5EBnjDNiFS5NWV9cpYJ5KKA7xPd3VB8/edit
