### ISSUE TITLE
Demo links don't work

### ISSUE THREAD

**Issue by niieani** [w3c/longtasks#92]
Hi!

Neither of these links cited in the README work :( 

> w3c.github.io/longtasks/render-jank-demo.html
> w3c.github.io/longtasks/demo.html

Looks like they were removed by @npm1 in [this commit](https://github.com/w3c/longtasks/commit/c5ba3b81a3f45cb365eeeeacad4784b343fbeb36). 

Hope they can be brought back!

Thanks 🙇

**Comment by npm1** [comment]
Oops, thanks for pointing this out, will send a PR sometime next week!

**Comment by gonnavis** [comment]
Hello, is there any progress?

**Comment by npm1** [comment]
Sent a PR to restore the demo

**Comment by npm1** [comment]
They still don't work :) I think I need to put them on gh pages branch
